### ISSUE TITLE
Document that `PowerShell-ctypes` is needed for the hooks to run

### ISSUE THREAD

**Issue by MatejKafka** [jborean93/PSDetour-Hooks#1]
Otherwise, you get the following error:
```
The term 'New-CtypesLib' is not recognized as a name of a cmdlet, function, script file, or executable program.
```

**Comment by jborean93** [comment]
Sorry I thought I got rid of any references for this module, I'll have to update that.

**Comment by jborean93** [comment]
The commit https://github.com/jborean93/PSDetour-Hooks/commit/b3bd13561a4ff7194f2bbb7119295ffd423f264d removes this dependency. Thanks for the report!
